# Generated by Django 6.0.5 on 2026-05-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosmart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('Eletrônicos', 'Eletrônicos'), ('Químicos', 'Químicos'), ('Orgânicos', 'Orgânicos'), ('Recicláveis', 'Recicláveis')], max_length=50)),
                ('descricao', models.TextField()),
                ('como_descartar', models.TextField(help_text='Separe os itens por quebra de linha')),
                ('cuidados', models.TextField(blank=True, help_text='Separe os itens por quebra de linha')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
