# Generated by Django 6.0.5 on 2026-05-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosmart', '0002_conteudoeducativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
